name: My build action requiring more space
on: push

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    steps:
      - name: Maximize build space
        run: |
          df -h
          rm -rf /opt/ghc
          rm -rf /usr/local/lib/android
          rm -rf /usr/share/dotnet
          df -h
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Free space:"
          df -h
